name: Automated Daily Commit with Emojis

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute for demonstration; adjust as needed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Update Log File
        run: echo "Update made at $(date '+%Y-%m-%d %H:%M:%S')" > update_logs.txt

      - name: Configure Git
        run: |
          git config --global user.email "rxmxdhxni@gmail.com"
          git config --global user.name "dante4rt"

      - name: Commit and Push Changes If Any
        run: |
          emojis=("ğŸ‰" "ğŸš€" "âœ¨" "ğŸ”¥" "ğŸŒˆ" "ğŸ’¥" "ğŸ€" "ğŸš€" "ğŸ’«" "ğŸˆ")
          emoji_index=$(($RANDOM % ${#emojis[@]}))
          selected_emoji=${emojis[$emoji_index]}
          commit_message="Enhanced daily update: $(date '+%Y-%m-%d %H:%M:%S') $selected_emoji"

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
          else
            git pull --rebase  # Ensure the local branch is up-to-date with remote
            git add -A
            git commit -m "${commit_message}"
            git push
